targets:
  $default:
    builders:
      socket_io_client_generator|socket_io_generator:
        enabled: true
        generate_for:
          - lib/**
          - example/**
builders:
  socket_io_generator:
    import: "package:socket_io_client_generator/src/builder.dart"
    builder_factories: ["socketBuilder"]
    build_extensions: {".dart": [".socket.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"] 