name: socket_io_client_generator
description: "Socket io client generator for Flutter - generates files that subscribe to Socket.IO events and redirect them to streams"
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^3.1.2
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  source_gen: ^2.0.0
  code_builder: ^4.10.1
  dart_style: ^3.1.0
  analyzer: ^7.3.0
  build: ^2.5.4
  pub_semver: ^2.2.0
  socket_io_client_gen_annotations:
    git:
      url: https://github.com/KlaysKAS/socket_io_client_gen_annotations.git
      ref: v0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
